src/main/perf/SearchTask.java
IndexSearcher.createNormalizedWeight() has been removed in master.
=> Fix compilation on master

src/python/benchUtil.py, src/python/competition.py, src/python/searchBench.py
This is useful for the work we have been doing on MaxScore/WAND and now indexing impacts in postings lists.
=> Add an option to not check total hit counts.

src/python/benchUtil.py
This allows to leverage the MR JAR.
=> Use JAR file for lucene/core rather than the classes folder. 

src/main/perf/IndexAndSearchOpenStreetMaps.java
Add new option (-shape) to index and search points using LatLonShape …approach. It supports querying by box and polygon
=> Add new index and search option for GeoPoints using LatLonShape

src/main/perf/IndexAndSearchOpenStreetMaps.java, src/python/writeGeoGraphs.py
Currently the GeoBenches for large polygons are not running,
=> Add missing useGeo3DLarge condition for polygons

src/python/writeGeoGraphs.py
Annotation for latest development.
=> Add annotations for LUCENE-8687

src/main/perf/RandomQuery.java
Currently it does not compile.
=> Add abstract method Query#visit

src/main/perf/IndexAndSearchOpenStreetMaps.java
=> QueryRelation now lives in ShapeField

src/python/runGeoShapeBenches.py, src/python/writeGeoShapeGraphs.py
This PR adds nightly capabilities to GeoShape Benchmarks. I have run them locally for ~1month of data points and the results can be seen here:
http://home.apache.org/~ivera/geoshapebench.html
=> Add nightly capabilities to GeoShape benchmarks

src/main/perf/IndexAndSearchShapes.java, src/python/runGeoShapeBenches.py, src/python/writeGeoShapeGraphs.py
Add contains support for IndexAndSearchShapes
=> Add contains support to LatLonShape

src/main/perf/IndexAndSearchShapes.java
This is a new addition to the API, it should be after that the current approach.
=> Use LatLonshape#newPointQuery for point queries

src/main/perf/IndexAndSearchOpenStreetMaps.java, src/main/perf/IndexAndSearchShapes.java, src/python/runGeoShapeBenches.py
This capability was added in Lucene-8707
=> Add distance query for LatLonShape

src/main/perf/IndexAndSearchOpenStreetMaps.java
This issue adds the possibility to have different planet models.
=> Fix compiler errors after LUCENE-9150

src/main/perf/IndexAndSearchOpenStreetMaps.java
See https://issues.apache.org/jira/browse/LUCENE-9148.
=> Use new Lucene 86 points codec

src/main/perf/TaskParser.java, src/python/benchUtil.py
- Correct where build.gradle should be looked up
- Correct how query term is extracted for dayofyeardvsort task
Closes https://github.com/mikemccand/luceneutil/issues/66
=> Small edits

src/fst/builder.py, src/python/IndexChart.py, src/python/QPSChart.py, src/python/WikipediaExtractor.py, src/python/benchUtil.py, src/python/competition.py, src/python/nightlyBench.py, src/python/searchBench.py, src/python/setup.py
I'm not sure this makes sense here, but [Python2 is no longer supported since Jan 1, 2020](https://www.python.org/doc/sunset-python-2/) (as everybody may know).
This is a draft pull request to support Python3 along with Python2 by shared code and could help gradual upgrade to Python3. It works for me with Python 2.7 and 3.5+. It's still incomplete (not all scripts are covered); if you are interested, I'd try to make a complete patch.
=> Support Python3 along with Python2

pom.xml, src/main/perf/TestAnalyzerPerf.java, src/python/runAnalyzerPerf.py, src/python/sumAnalyzerPerf.py, src/python/wikiXMLToText.py
Closes #64
I've added JapaneseAnalyzer in TestAnalyzerPerf.java. And also add kuromoji directory to classpath in runAnalyzerPerf.py
I'm not sure it is OK or not to add JapaneseAnalyzer test with jawiki in TestAnalyzerPerf.java. If we should separate it, please let me know.
Before running perf test, I've made `jawiki-20200620-lines.txt`using `WikipediaExtractor.py` and `wikiXmlTo.py`.
Unfortunately, I couldn't find how to make wiki lines text from wikipedia XML. 
So I did the following procedure...
1. Download and unzip2 `jawiki-20200620-pages-articles.xml.bz2`from dumps.wikimedia.org
2. Run `python src/python/wikiXMLToText.py jawiki-20200620-pages-articles.xml jawiki-lines.txt`
* I've changed `wikiXMLToText.py` for handling no-username page. Add empty username in `attr` dictionary. line …
=> Add Kuromoji to AnalyzerPerf test

.gitignore, build.xml, src/main/WikiVectors.java, src/main/perf/KnnQuery.java, src/main/perf/LineFileDocs.java, src/main/perf/SearchPerfTest.java, src/main/perf/SearchTask.java, src/main/perf/TaskParser.java, src/main/perf/VectorDictionary.java, src/python/benchUtil.py, src/python/buildAndCheckIndexForeverUntilCorrumption.py, src/python/competition.py, src/python/constants.py, src/python/knnPerfTest.py, src/python/nightlyBench.py, src/python/nrtPerf.py, src/python/searchBench.py, tasks/vector.tasks
Utilities for creating document and query embedding data files
A new benchmark task for HNSW vector search
A KNN graph search benchmarking utility for exploring parameters
=> HNSW benchmarking setup and tools

src/main/perf/SearchTask.java
Fix for https://github.com/mikemccand/luceneutil/issues/101
=> Fix vector field retrieval

src/main/perf/IndexState.java, src/main/perf/Indexer.java, src/main/perf/LineFileDocs.java, src/main/perf/SearchPerfTest.java, src/python/example.py, tasks/titlebdv.tasks, tasks/wikimedium.10M.nostopwords.tasks, tasks/wikimedium.10M.tasks, tasks/wikimedium.1M.nostopwords.tasks, tasks/wikinightly.tasks
Added `BrowseDateSSDVFacet` task since we can now support it.
=> Added hierarchical SSDV task

src/main/perf/facets/BenchmarkFacets.java, src/main/perf/facets/IndexFacets.java, src/main/perf/facets/README.md
Upgraded the high cardinality facets test to warm up and run multiple times in order to get more accurate results.
=> Upgraded high cardinality facets benchmark to be more accurate

src/main/perf/facets/BenchmarkFacets.java
We now have getTopDims functionality in facet and I added it to benchmark as well.
https://github.com/mikemccand/luceneutil/issues/175
=> Add getTopDims to benchmark

src/main/perf/LineFileDocs.java, src/python/buildBinaryLineDocs.py
1. Changes the script that build the binary LFDs and added ID to each line
2. Changes the way of assign IDs in `LineFileDocs.java`
=> Make ID assignment deterministic

src/python/nightlyBench.py
Hi @mikemccand, 
Please help test this on your machine and let me know if there's any problem LOL.
I set the `numThreads` to `cpu_count`, but please modify it accordingly if need.
Patrick
=> Enable nightly bench to use multiple threads

src/python/benchUtil.py, src/python/competition.py
=> Increase the default topN to 100.

README.md
It takes me some time to figure out how to run it, @msokolov let me know if I have missed anything, thanks!
=> Update README.md for higher dimensional vectors

README.md
Updating README.md with info about using wikimediumall corpus.
=> Update README.md with info about using wikimediumall corpus

src/main/KnnGraphTester.java
For awhile now, KnnGraphTester just hasn't returned the actual vectors visited. It only returns the number of vectors returned, which isn't very helpful.
Taking advantage of some new extension points for knn queries, I corrected the output.
=> Fix vector visited count for KnnGraphTester

src/main/KnnGraphTester.java
This adds more graph stats outputs for HNSW. 
- Adds connectiveness percentage for each layer starting from the graph entry point
- Adds histogram output for number of connections for each layer (not just the bottom)
Additional adjust the following:
- Adds new `randomCommits` input for aggressively testing merging by randomly calling `iw.commit()`
- Allows for `forceMerge` to run even without reindex. This is helpful for benchmarking & testing the differences between multiple segments and then force-merging them to a single graph.
=> Add better graph stats outputs & new input option

src/main/knn/KnnGraphTester.java, src/main/knn/KnnIndexer.java
This:
- adds back quantization support lost due to refactor
- Adds 4bit quantization support, with and without compression
- Allows force-merge parallelization without specifying an executor (to use intra-merge threads provided by the scheduler).
=> Adding 4bit quantized support

src/main/perf/IndexAndSearchOpenStreetMaps.java
We added search concurrency to lucene bench, let's add it as well; to the geo benchmarks. I added a new otional parameter called searchConcurrency that accepts an integer greater or equal to zero. This is how it works:
- if not added, the searches will be run with the number of threads defined by `Runtime.getRuntime().availableProcessors();`
- if zero, it runs with no search concurrency (like now)
- if a positive integer, this will the number of threads in the threadpool.
=> Add search concurrency to geo benchmarks

src/python/writeGeoGraphs.py
And here is the annotation for https://github.com/mikemccand/luceneutil/pull/285
=> Add annotation to geo benchmarks for search concurrency

src/main/knn/KnnGraphTester.java
also print mean graph delta as part of stats
=> parallelize exact-knn computation; 

src/python/nightlyBench.py, tasks/wikinightly.tasks
These queries are interesting because they are less favorable to dynamic pruning, and things like evaluating the maximum score per block or re-partitioning can be expensive.
=> Add nightly task for disjunctions of many terms.

src/main/knn/KnnGraphTester.java
This update refactors the prefiltering logic to utilize a RandomQuery, ensuring consistency in IDs between the exact and approximate searches during recall computation. 
Postfiltering's recall remains broken because the reproducibility of RandomQuery is influenced by the presence of other clauses in the query.  Addressing this issue will require further investigation, but first, we need to resolve the prefiltering recall, as it is the primary use case for filtering.
Fixes #326
=> Refactor Prefiltering Logic in KnnGraphTester

build.xml, src/main/knn/KnnGraphTester.java, src/python/notation.py
Adds an annotation for the pre-filtered search improvements.
This also contains changes I found useful when doing pre-filtered benchmarking and other potpourri.
=> Add annot for Lucene#14160 and improve KnnGraphTester prefiltered testing

README.md, src/python/initial_setup.py
setup.py has special meaning and this name confuses tools, editors, language servers, etc
=> rename setup.py to initial_setup.py

src/python/notation.py
https://benchmarks.mikemccandless.com/2025.04.14.18.05.20.html
https://benchmarks.mikemccandless.com/PKLookup.html
=> Annotation for #14333
