src/main/perf/IndexAndSearchOpenStreetMaps.java

Due to LatLonShape API evolution we need to provide a query type, in this case INTERSECTION (although CONTAINS might be possible as well).

Fix compile error: Add query type (INTERSECTION) to LatLonShape queries.

---

src/main/perf/SearchPerfTest.java
src/python/benchUtil.py
src/python/competition.py
src/python/example.py
src/python/sendTasks.py

Typical analytical workloads involve concurrent segment reads and
use read latencies as an important metric for evaluating performance.
This commit introduces those two functionalities

Introduce Analytical Benchmarking

---

src/main/perf/LocalTaskSource.java
src/main/perf/SearchPerfTest.java

I found that when running with SEARCH_TASKS > 1, "expensive" tasks were stealing threads from "cheap" tasks making results meaningless; basically all tasks would appear to have the same QPS. This change groups the (shuffled, repeated) tasks by category before executing them. There would probably still be a little bit of overlap at the boundaries between one run of tasks and the next, but I see dramatically more repeatable results now

Group tasks by category when search threads > 1

---

src/main/perf/IndexAndSearchOpenStreetMaps.java

It is currently pointing to Lucene84.

Update IndexAndSearchOpenStreetMaps to lucene86

---

src/python/example.py

Trivial patch to change directory names in the template `example.py` in accordance with README. This eases the first attempt to run the benchmarks on local machines.
Thanks.

Update example.py in accordance with README

---

src/python/benchUtil.py

In https://github.com/apache/lucene-solr/commit/2991acf8fffe9dbeda20c24479b108bfb8ea9257#diff-0a9e963d0e9ba82d79db98b8903b5c56, hppc version was upgraded to 0.8.2, so this tool also should refer hppc-0.8.2 since it fails with the latest Lucne master.
Compiling log message:
```
RuntimeError: unable to locate hppc-0.8.1.jar dependency for lucene/facet!
```
It would be preferable not to hard-code the correct artifact version though, we'd need to fix it manually for the moment (?)

Update hppc artifact version to 0.8.2

---

README.md

It might be useful we have a note for creating line doc files from the original Wikimedia dumps (especially for devs who want to have a non-English corpus; like #69).

Add notes for creating line doc file from XML dump

---

src/python/benchUtil.py

@mikemccand I'm sorry I broke `benchUtil.py` with #72 !
`shlex.split()` should be used instead of `str.split()` when passing the command to Popen, otherwise some commands (e.g. invoking `javac`) will fail.

Fix a bug benchUtil.run() method 

---

README.md
src/python/WikipediaExtractor.py
src/python/combineWikiFiles.py
src/python/runAnalyzerPerf.py
src/python/wikiXMLToText.py

I worked through the tricky steps from https://github.com/mikemccand/luceneutil/pull/69 to build a new line-docs-file for the newly added Kuromoji analyzers benchmark, and got it working in a new tool, `createJapaneseWikipediaLineDocsFile.py`.
I also had to make a few more python3 fixes to the dependent tools `WikipediaExtractor.py` and `wikiXMLToText.py` to get the whole script working under python 3.8.
It works, and produces a line docs file in the end, and I'm able to `runAnalzyersPerf.py` using it, but the problem is that the file I got in the end ([copied here](http://home.apache.org/~mikemccand/new-jawiki-20200620-lines.txt.lzma) is larger (~2.9 GB) than the one from https://github.com/mikemccand/luceneutil/pull/69 (~2.5 GB, [copied …

Add tool to download and create the ja-wiki-2020620 line docs file

---

src/python/benchUtil.py
src/python/competition.py

This switches our usage of subprocess.Popen from the version that uses a string command to the one that uses a list. This is just a cleanup. I think it's better because it avoids string formatting and concatenation (which we sometimes also split), and the need to wrap some arguments in double quotes to protect them from the shell. It also just looks cleaner to me.

Switch subprocess execution to arg list instead of string

---

src/python/benchUtil.py

This adds a p-value column to luceneutil's output. The p-value is to be interpreted as the probability that the observations in the two conditions were drawn from the same underlying distribution; that is, that there is no difference. Typically p < 0.05 is treated as a statistically significant difference.
Questions: 
1. should we make this the default sort (rather than percent difference, which must be eyeballed against std.dev.)
2. should we group the results into significant/insignificant?

Add a p-value column to the report, and make it sortable

---

src/main/perf/LineFileDocs.java
src/python/benchUtil.py
tasks/wikimedium.10M.nostopwords.tasks

Sort optimization introduced in https://github.com/apache/lucene-solr/pull/1351
depends on numeric fields being indexed both as doc_values and points.
This PR does the following:
- add a LongPoint field – lastModLP, last modified timestamp
- add an IntPoint field – dayOfYearIP, day of the year of the last modified timestamp
- add sort on the last modified timestamp to wikimedium.10M.nostopwords.tasks
- don't fail a task if hitCounts don't match in benchUtil.py. As we
don't collect all hits in the optimized runs, we don't expect hits total
to match.

Index points to benchmark sort optimization

---

src/python/benchUtil.py

if `len(baseQPS) > 2` an expression `2 / len(baseQPS)` = 0,
causing a division by 0 error for the t-value calculation.
This patch fixes it to produce decimal number instead of 0.

Fix division by 0 in t-value calculation

---

.dir-locals.el
src/main/WikiVectors.java
src/main/perf/Indexer.java
src/main/perf/LineFileDocs.java
src/main/perf/NRTPerfTest.java
src/main/perf/SearchPerfTest.java
src/main/perf/SearchTask.java
src/main/perf/TaskParser.java
src/python/benchUtil.py
src/python/competition.py
src/python/constants.py
src/python/setup.py
tasks/wikimedium.10M.nostopwords.tasks

setup.py can now download a GloVe vector embeddings file
WikiVectors.java computes document-embeddings from those per-term embeddings
Indexer has new arguments -vectorFile <file> and -vectorDimension <dim>:
These expect the output from WikiVectors and index vectors in a field called "vector".
SearchPerfTest and python framework accept -vectorField <fieldName> and when present,
the vector value in the named field is retrieved for every matching hit

VectorValues test support

---

src/main/perf/TaskParser.java

I wanted to add a new type of search task (for matching w/vectors), but I found this file kind of scary. I believe one should learn to face their fears, so this PR confronts the terror head-on, refactoring into a (more) functional style, collecting local variables that we share (and some of which we mutate) across many code blocks into a new TaskBuilder object, moving the code blocks into named functions.

TaskParser cleanup, breaking monolith into functions

---

README.md

Update README.md with updated changes for running with gradle, adding clearer instructions for downloading lucene checkouts.
The current README is confusing in terms of the final directory structure (lucene should ideally be checked out in a folder called `lucene_baseline` and `lucene_candidate`) and requests the reader to run `gradle jar` in the lucene dir, which should ideally be run in the `lucene-solr` directory.

Update README.md with gradle commands, git clone destination instructions

---

src/python/setup.py

The glove 6B download seems to be pointing to the wrong location.
The tuple ('glove.6B.zip', 'http://nlp.stanford.edu/data/glove.6B.zip') seems
to make the downloader point to
http://nlp.stanford.edu/data/glove.6B.zip/glove.6B.zip which does not exist.
http://nlp.stanford.edu/data/glove.6B.zip does however exist. This commit
changes to specifying only http://nlp.stanford.edu/data/ as the base URL.

Fixes glove 6B download

---

src/python/profiling.jfc

In this commit we touch on essentially 2 kinds:
- Runtime, such as GCs, CPU and Compilation enables us to see more of what
the JVM is doing, and how it is performing.
- Machine & JDK setup. Records the CPU information, JVM information and
whichever flags end up being enabled by the JVM.

Adds more profiling to the profiling.jfc file.

---

src/main/perf/Indexer.java
src/python/constants.py

This fixes the performance of BrowseDayOfYearTaxoFacets,
BrowseDateTaxoFacets, BrowseMonthTaxoFacets facets
| Task | Mainline  | Updated codec  |
|---|---|---|
| BrowseMonthSSDVFacets  | 2.94  | 2.93 |
|  BrowseDayOfYearSSDVFacets | 2.76  | 2.75 |
| BrowseDayOfYearTaxoFacets  | 0.71  | 1.23 |
| BrowseDateTaxoFacets  | 0.71  | 1.23 |
|    BrowseMonthTaxoFacets | 0.74  | 1.42 |

Fix taxonomy index DocValues to use BEST_COMPRESSION mode

---

src/main/perf/BenchRearranger.java
src/main/perf/Indexer.java
src/main/perf/PerfUtils.java
src/main/perf/StringFieldDocSelector.java
src/python/benchUtil.py
src/python/competition.py

* Added a `rearrange` option to `Index` class in `competition.py` which configs the arrangement desired. E.g. 555 means 5 large, 5 medium, 5 small. For detailed explanation please refer to `BenchRearranger.java`
* Added a `StringFieldDocSelector` class to select documents that has certain string indexed (this probably should belong to lucene/misc)
* Added a `BenchRearranger` class holding execution logic of benchmark rearrangement
* Added rearrange logic to `Indexer.java`

#103: Add option to construct deterministic index using IndexRearranger

---

src/main/perf/IndexAndSearchOpenStreetMaps.java
src/main/perf/IndexAndSearchShapes.java

The CodecReader does not implement Accountable any more (https://issues.apache.org/jira/browse/LUCENE-9387) so this method does not exists.

Remove call to CodecReader#ramBytesUsed() from geo benchmarks

---

src/python/profiling.jfc

This PR adds Socket and File events to the profiling. These events
allows for tracking how much File & Socket I/O is done. Interestingly,
these events can also tell the stack trace of the I/O as well as the
path (for files) and host + port (for sockets). Only the bytes read are
recorded, so e.g. the path of a http request would not be recorded.
Some notes:
- I tested the performance impact of this change on some wiki_all_10M
indexing and searching. For indexing, it averaged at 0.2% slower. For
searching it averaged at 0.5% slower. At N=4 I'm pretty sure that it's
not statistically relevant, but at least it won't kill the benchmarks. I
would expect the impact to be less on the proper benchmarking machine,
since my machine is CPU-bound.
- File I/O essentially only looks at java.nio.File, …

Adds Socket I/O and File I/O profiling

---

src/main/perf/BenchRearranger.java
src/main/perf/Indexer.java
src/main/perf/LineFileDocs.java

Make id assignment deterministic by moving the id assignment to the thread that handles input.
Also includes some minor print out changes that is helpful to debug rearrange.

#121: Make id assignment deterministic

---

src/main/perf/LineFileDocs.java
src/python/nightlyBench.py

Add idNDV NumericDocValue field and let nightly benchmark depend on it to produce consistent results
Local test shows this resolves issue #121

#121: Add idNDV NumericDocValue field

---

README.md

Noticed repo was still pointing to lucene-solr.git and this should now be just lucene.git.  Also noticed typo in comment path example.

Updated in readme the path for lucene repo, fixed typo

---

src/main/perf/KnnQuery.java

Fixes compile error due to API change in Vector search.

VectorValues#search has been moved to LeafReader

---

src/main/perf/BenchRearranger.java
src/main/perf/Indexer.java

* Revert a reverted bug fix for `IndexRearranger`
* Delete the temp dir after rearranging

#125 clean up temp disk usage after rearrange (and bring back a bug fix)

---

src/main/perf/TaskParser.java
src/python/competition.py
src/python/constants.py
tasks/disjunctionIntensive.tasks
tasks/disjunctionRealistic.tasks
tasks/disjunctionSimple.tasks

Disjunctions, and particularly positional queries with inner disjunctions, are not really covered at the moment. Building off of existing work for "multiPhrase", this PR adds tasks that test straight disjunctions, and positional queries with nested disjunctions (SpanNearQuery with nested SpanOrQueries, and Intervals.ordered with nested disjunctions, both with and without rewriting to `pullUpDisjunctions()`).
NOTE: I think in order to work properly this may require a minor change in Lucene, to enable `DisjunctionIntervalsSource.toString()` to serve as a stable key on the python side:
```
@@ -120,7 +120,7 @@ class DisjunctionIntervalsSource extends IntervalsSource {
@Override
public String toString() {
-    return subSources.stream().map(Object::toString).collect(Collectors.joining(",", …
```

Add tasks for positional queries with nested disjunctions

---

src/main/perf/StoredFieldsBenchmark.java

This is an iteration over @rmuir's benchmark in #145 that changes the following:
- adds a warm-up so that timings don't include too much time spent on
compilation
- indexes 1M docs instead of 100k
- flushes every 100 docs instead of every document
- configurable mode (`BEST_SPEED` and `BEST_COMPRESSION`)

Add a stored fields benchmark.

---

.gitignore
src/main/perf/LineFileDocs.java
src/python/buildBinaryLineDocs.py
src/python/constants.py
src/python/createLineFileDocsWithRandomLabel.py
src/python/example.py
src/python/nightlyBench.py
tasks/wikimedium.10M.nostopwords.tasks
tasks/wikimedium.10M.tasks
tasks/wikimedium.1M.nostopwords.tasks
tasks/wikinightly.tasks

Related issue: https://github.com/mikemccand/luceneutil/issues/141
Here are some distribution stats I got from a test run for these labels:
```
Number of ords:
1780371
Singleton count:
1416244
Top 20 taxonomy counts: 
[RandomLabel.taxonomy, the] 372665
[RandomLabel.taxonomy, of] 276350
[RandomLabel.taxonomy, |] 189343
[RandomLabel.taxonomy, and] 183320
[RandomLabel.taxonomy, in] 164785
[RandomLabel.taxonomy, =] 155886
[RandomLabel.taxonomy, to] 127328
[RandomLabel.taxonomy, a] 117079
[RandomLabel.taxonomy, *] 65859
[RandomLabel.taxonomy, is] 63901
[RandomLabel.taxonomy, was] 56826
[RandomLabel.taxonomy, The] 55280
[RandomLabel.taxonomy, for] 55161
[RandomLabel.taxonomy, EMPTY_WORD] 49364
[RandomLabel.taxonomy, by] 47790
[RandomLabel.taxonomy, on] 46427
[RandomLabel.taxonomy, as] 46382 …
```

Added facet benchmark that chooses random words as labels

---

src/main/perf/OrdinalMapBenchmark.java

This was a suggestion from @rmuir to have something like the
`StoredFieldsBenchmark` but for `OrdinalMap` construction. Here's an example
output:
```
id: 12556.30082 msec
name: 12797.48203 msec
country_code: 3.79370 msec
time_zone: 9.48330 msec
```

Add a benchmark for OrdinalMap construction.

---

src/main/perf/SearchPerfTest.java
src/python/benchUtil.py
src/python/competition.py

#168 
Instead of `timeout` parameter (#171), I added `exitable` boolean option this time. When `exitable=True`, the directory reader is wrapped by ExitableDirectoryReader, where the timeout is `-1` (this is interpreted to Long.MAX_VALUE in `QueryTimeoutImpl` constructor).
Usage (`localrun.py`)
```python
comp.competitor('baseline', 'lucene_baseline',
index = index, concurrentSearches = concurrentSearches)
comp.competitor('exitable_directory_reader', 'lucene_candidate',
index = index, exitable = True, concurrentSearches = concurrentSearches)
```
A sampled result (with `-source wikimedium1m`)
```
TaskQPS baseline      StdDevQPS exitable_directory_reader      StdDev                Pct diff p-value
BrowseMonthTaxoFacets      166.54     (13.2%)       80.06     (17.7%)  -51.9% ( -73% -  -24%) …
```

Wrap directory reader by ExitableDirectoryReader when 'exitable' parameter is passed.

---

src/main/perf/facets/BenchmarkFacets.java

We now support the getAllChildren functionality in facet and it would be nice to add it to benchmark as well. Please see below for the benchmark results after adding getAllChildren.
```
Results after iteration 20
Time (ms) taken to instanciate FastTaxonomyFacetCounts: 4123.887288349999
Time (ms) taken to instanciate SSDVFacetCounts: 10977.917832749998
SSDV is 166.2% slower than Taxonomy
Time (ms) taken to get all dims for taxonomy: 2.79734245
Time (ms) taken to get all dims for SSDV: 1.1225765500000002
Taxonomy is 149.2% slower than SSDV
Time (ms) taken to get top dims for taxonomy: 0.26965845
Time (ms) taken to get top dims for SSDV: 0.0748355
Taxonomy is 260.3% slower than SSDV
Time (ms) taken to get top children of "address.taxonomy/TX" children for taxonomy: 2.8276866000000003
Time …
```

added getAllChildren to benchmark

---

src/python/benchUtil.py

benchUtil.py checks for hppc version 0.9.0, but raises the exception an incorrect version in the message if this dependency is not found.

benchUtil.py hppc version check inconsistency fix

---

src/python/benchUtil.py

Got to know in https://github.com/mikemccand/luceneutil/pull/188 that the hppc version being used by Lucene is 0.9.1

Changing the dependency to hppc-0.9.1

---

src/main/perf/IndexThreads.java
src/main/perf/LineFileDocs.java
src/main/perf/PKLookupTask.java

* Add the id docValue field so that we can use indexSort on id field
* Fix the bug where group index are claimed but not used, which eventually leads to missing document in the index when indexing using multiple threads

Add id docValue field, fix the concurrent bug when index using binary lfd

---

src/python/benchUtil.py
src/python/competition.py
src/python/constants.py
src/python/nightlyBench.py
src/python/vector-test.py

I feel like it's cleaner to write JFR files to logs dir - wdyt?
Also, made some small changes to enable wikimedium500 which is what setup.py sets up. It always bothered me that you could not check out run setup.py and then successfully run benchmarks; I think with this you will be able to.

move jfr to logs; run out of the box after setup.py using wikimedium500

---

src/main/perf/IndexThreads.java
src/main/perf/Indexer.java
src/main/perf/LineFileDocs.java

* Add a synchronized block to make sure group index and docs are both ready before starting indexing a new group
* Recycling the remaining document block when there's no more group index (since this means there's must be some groups that needs more documents)
Tested using a 10k docs binary LFD with group size of 10k (1 doc per group) and 400 (25 doc per group, near the ratio of what we have in nightly bench)

Further fixing concurrent bug while using binary LFD and group index

---

src/main/perf/LineFileDocs.java
src/main/perf/TaskParser.java
src/python/benchUtil.py

I _think_ this fixes the bug that showed up in the previous attempt to cutover to `KeywordField`, but I'm not entirely sure how to repro the last issue, so I can't verify the fix. Should running `wikimedium10k` expose the bug with the last attempt?

Cut over Wikipedia benchmark to KeywordField, take 2 (with bug fix)

---

src/main/perf/LocalTaskSource.java
src/main/perf/NRTPerfTest.java
src/main/perf/PKLookupTask.java
src/main/perf/PointsPKLookupTask.java
src/main/perf/RemoteTaskSource.java
src/main/perf/RespellTask.java
src/main/perf/SearchPerfTest.java
src/main/perf/SearchTask.java
src/main/perf/Task.java
src/main/perf/TaskParser.java
src/main/perf/TaskParserFactory.java
src/main/perf/TaskThreads.java
src/main/perf/UnparsedTask.java
src/python/competition.py

Created an `UnparsedTask` and all it does is to parse itself to other tasks when running.
Make every TaskThread carry one TaskParser and pass it into `Task.go` method
Test with wikimedium10k
before change:
```
TaskQPS baseline      StdDevQPS candidate      StdDev                Pct diff p-value
IntNRQ     2759.40      (6.0%)     2861.93      (6.0%)    3.7% (  -7% -   16%) 0.051
HighTermMonthSort     2314.12     (12.3%)     2419.55     (10.4%)    4.6% ( -16% -   31%) 0.207
BrowseRandomLabelSSDVFacets     1387.03      (8.3%)     1452.92      (8.5%)    4.8% ( -11% -   23%) 0.073
OrHighMed     2057.11      (9.9%)     2186.84      (8.7%)    6.3% ( -11% -   27%) 0.033
OrHighHigh     1699.57      (8.5%)     1811.58      (9.4%)    6.6% ( -10% -   26%) 0.020
MedSloppyPhrase     1290.72      (8.7%) …
```

Make task parsing part of search

---

README.md
src/python/competition.py
src/python/example.py
src/python/setup.py

Adds argparse support to `setup.py` and `example.py`, which is used to create `localrun.py`. This removes dependency from positional sys.argv variables. Also updated the README to help with minor surprises I ran into during setup.
```bash
% python3 src/python/setup.py -h  
usage: luceneutil setup [-h] [-d]
Benchmarking setup for lucene
options:
-h, --help            show this help message and exit
-d, -download, --download
Download datasets to run benchmarks. A 6 GB compressed Wikipedia line doc file, and a 13 GB vectors file is downloaded from Apache
mirrors
```
```bash
% python3 src/python/example.py -h                                  
WARNING: Gnuplot module not present; will not make charts
usage: Local Benchmark Run [-h] [-s SOURCE] [-c]
Run a local benchmark on provided source …
```

Add argparse support to python runner scripts

---

README.md
src/python/benchUtil.py
src/python/competition.py
src/python/example.py

In its current form, `luceneutil` expects a directory structure with baseline repo present in `$BENCH_DIR/lucene_baseline` and candidate repo in `$BENCH_DIR/lucene_candidate`. 
While a lot of existing users already work with this setup, it adds some additional steps in certain scenarios like when your candidate is already checkout out in a different location, or when candidate is a different upstream branch on the baseline repo (e.g. fetching and benchmarking a PR locally).
This change leverages the `argparser` support added in #230 and adds arguments for baseline and candidate repo paths to the benchmark script. Both arguments are optional. If skipped, the benchmark script picks code from `$BENCH_DIR/lucene_baseline` and `$BENCH_DIR/lucene_candidate` respectively.
It also adds a `-r / …

Allow passing Baseline and Candidate paths via script args

---

src/main/KnnGraphTester.java

Sets index writer config codec for force merge operation in KnnGraphTester. Fixes issue where merged segments are built with different algorithm parameters than segments created from createIndex.
This raised a false alarm bug in https://github.com/apache/lucene/issues/12570. PR was originally raised in lucene but I forgot about it: https://github.com/apache/lucene/pull/12002. 
Tested locally with the vector-task-100d

Set algo params for force merge in KnnGraphTester

---

src/python/nightlyBench.py
tasks/wikinightly.tasks

Looking into the [Tantivy benchmark](https://tantivy-search.github.io/bench/) highlighted that there are interesting cases that are not covered by our nightly benchmarks. For instance, MAXSCORE splits clauses into essential and non-essential clauses, but our nightly benchmarks only really benchmark the case when there is a single essential clause (with `OrHighMed` because there is one clause whose scores dominates, and with `OrHighHigh` because there are so many documents that have both terms that `MAXSCORE` quickly realizes that the clause with the maximum score is required for a hit to be competitive anyway).
This adds a few more categories whose performance would be interesting to track. I'm expecting the performance of these queries to often react very differently to changes in query …

Add more interesting tasks for top-k hits on boolean queries.

---

src/main/IndexToFST.java
src/main/KnnGraphTester.java
src/main/perf/Indexer.java
src/python/benchUtil.py
src/python/competition.py
src/python/nightlyBench.py

I added `hnswThreadsPerMerge` and `hnswThreadPoolCount` to `Indexer` and `competition.Index/newIndex`, and fixed nightly to pass these from its local `constants.py` file.
I have yet to disable strict top N checking for KNN hits when concurrency is enabled -- I'll do that as a followon commit after testing on nightly box!
Closes #239.

Add concurrent HNSW merge options to benchmarking & nightly benchmark

---

src/python/competition.py
src/python/constants.py

Removing wikibig_tasks references, wikibig is supposed to use the wikimedium tasks.
Doing the changes to constants.py and competition.py

Removing wikibig_tasks references, wikibig is supposed to use the wikimedium tasks

---

src/main/perf/Indexer.java

This commit has `quantizeKNNGraph` return a quantized format, where as the else branch returns a raw format.

Have quantizeKNNGraph return a quantized index

---

src/python/nightlyBench.py

The default CheckIndex behavior was recently changed to only verify checksums. I'd like nightly benchmarks to keep doing integrity checks.

Switch back CheckIndex nightly runs to level 2.

---

README.md
src/python/infer_token_vectors_cohere.py
src/python/knnPerfTest.py

This dataset contains vectors of higher dimensions of 768. This dataset contains a pre-processed version from Wikipedia suitable for semantic search.
The problem with current datasets generated by `infer_token_vectors.py` file is that they are generated for single tokens out of context. Thus, they don't represent the true embeddings, and hence the produced recall of vector search on them is not good.
Cohere/wikipedia-22-12-en-embeddings dataset represent true embeddings and we can
show very good recall of Lucene vector search on them.

Add Cohere/wikipedia-22-12-en-embeddings dataset for vector search

---

build.xml
src/main/knn/KnnGraphTester.java
src/main/knn/KnnIndexer.java
src/main/knn/KnnIndexerMain.java
src/main/knn/VectorReader.java
src/main/knn/VectorReaderByte.java
src/main/knn/VectorReaderFloat32.java
src/python/knnPerfTest.py

In this PR
1. moved the current KnnGraphTester to `knn` package.
2. Extracted KnnIndexer class out of KnnGraphTester code so that the logic can be reused.
3. Extracted some more classes from KnnGraphTester to avoid bloating it as a coding best practice.
Tests :
``` 
ant build
python src/python/knnPerfTest.py
```
Also tested by passing the `-indexPath` to KnnGraphTester from knnPerfTest.py. Works fine. 
Was able to run the command correctly and get output like
|recall	|avgCpuTime	|numDocs	|fanout	|maxConn	|beamWidth	|totalVisited	|reindexTimeMsec	|selectivity	|prefilter|
|---|---|---|---|---|---|---|---|---|---|
|0.971	| 0.71	|10000	|0	|16	|100	|1339	|7013	|1.00	|post-filter|

Extracted KnnIndexer class out of KnnGraphTester and moving to a knn package

---

src/main/perf/TaskParser.java

API changed for Lucene 10, when `BooleanClause` became a record: https://github.com/apache/lucene/pull/13261

Update BooleanClause attributes access after #13261

---

src/main/perf/IndexState.java
src/main/perf/SearchPerfTest.java

We're considering [building ordinal maps eagerly](https://github.com/apache/lucene/issues/11601). This can already be done to some extent using the current API. This PR shows how that should be done.
I'm don't know if the change is worth committing as is. The reader states that we compute are unused and there's no useful performance data we would be getting.
Testing: `python3 src/python/localrun.py -source wikimedium10k -facets -nrt`

Demonstrate ordinal map building on refresh

---

src/main/perf/Args.java
src/main/perf/Indexer.java
src/python/benchUtil.py
src/python/competition.py
src/python/nightlyBench.py

This switches from custom values of `disableIOThrottle` and `maxConcurrentMerges` to CMS's default values.

Use CMS defaults.

---

src/main/knn/KnnGraphTester.java

One other thing is the transient dependency on hppc. 
It would be really good if luceneutil was updated so it could download and use hppc directly (via ant, or gradle, etc.). But I suck at build systems and they make me want to throw my laptop, so, I didn't bother with that.

Fix KnnGraphTester compilation with latest lucene changes

---

src/main/perf/SearchPerfTest.java
src/python/benchUtil.py
src/python/competition.py
src/python/example.py
src/python/nightlyBench.py

We're making concurrenty search more of a first-class citizen, and hopefully it will soon even be the default in Lucene. So let's start better exercising code paths for concurrent search in nightly benchmarks by configuring an executor, but bounding it to a single thread for now to contain noise.
Closes #210

Run nightly benchmarks with a single thread executor.

---

src/python/example.py

After #271 we now see a `NumberFormatException` if `-searchConcurrency` isn't specified when running benchmarks through `localrun.py`. This proposes specifying `-1` as a default value.

Provide a default value for searchConcurrency in example.py

---

src/python/constants.py
src/python/example.py
src/python/vector-test.py

Changes to make it easier to run `vector-test.py` for knn benchmarks. Includes the following:
1. Picks `java` exec path from `$JAVA_HOME` if configured.
2. Uses `argparse` for `vector-test.py` configurations
3. Allows setting `baseline` and `candidate` repository locations via env variables.
__
```bash
% python src/python/vector-test.py -h
Using java from: /home/vigyas/openjdk/jdk-22/bin/
WARNING: Gnuplot module not present; will not make charts
no perf executable; will not collect aggregate CPU profiling data
usage: Local Vector Benchmark Run [-h] [-s SOURCE] [-searchConcurrency SEARCHCONCURRENCY] [-b BASELINE] [-c CANDIDATE]
Run a local vector test benchmark on provided source dataset.
options:
-h, --help            show this help message and exit
-s SOURCE, -source SOURCE, --source …
```

Improve vector-test run options using arg parse and env vars

---

src/main/perf/IndexState.java
src/main/perf/NRTPerfTest.java
src/main/perf/SearchPerfTest.java
src/main/perf/TaskThreads.java

IndexSearcher was recently updated to make the calling thread contribute to search execution. This means that searching with an executor of 8 threads uses 9 threads in practice if `IndexSearcher#search` is called from outside of the executor. This change moves the `IndexSearcher#search` call to the executor to better honor luceneutil's `-searchConcurrency` parameter.

Run search tasks in IndexSearcher's executor.

---

src/python/QPSChart.py

Minor bug fix in comparing tuple values within an array. 
Fixes exception:
```python
WARNING: failed to generate QPS diff chart chartData=[('LowTermVector', 222.18008690965422, 230.1825676551332, 204.2715128301673, 234.3230073144681, 0.04771273811822019), ('Med
TermVector', 236.89980286169003, 246.16356758844938, 217.39604810565294, 252.6236556383957, 0.10927867133559532), ('AndHighLowVector', 203.28180349595337, 210.37278966183842, 189.33638831630697, 213.65397665540257, 0.05972814797216097), ('HighTermVector', 212.3340958310362, 219.9530466061183, 197.4996169350486, 225.19411984655903, 0.13526436593711066
), ('AndHighHighVector', 182.4618977509103, 189.22062876057603, 170.19781709851654, 194.3188476521071, 0.20078875662911377), ('AndHighMedVector', 201.97941896307853, 210.327913 …
```

Fix bug in generating QPS diff chart

---

build.xml
src/main/knn/KnnGraphTester.java
src/main/knn/VectorReader.java
src/main/knn/VectorReaderByte.java
src/python/knnPerfTest.py

While benchmarking already quantized or `byte` vectors, I ran into various bugs. 
This pr fixes them.
- Corrects true nearest-neighbor calculation to use the `byte` comparator as our score transformations are different between bytes and floats
- Adds a knn byte query (previous we always tried a float query, which would just break)
- Fixed another weird vector reader bug which would always read just the first vector as calling `bytes.get` resets the bytes read.

Various byte vector benchmark fixes

---

.gitignore
README.md
build.gradle
build.xml
gradle/knn.gradle
gradle/wrapper/gradle-wrapper.properties
gradlew
gradlew.bat
src/main/build.gradle
src/main/knn/KnnGraphTester.java
src/python/common.py
src/python/infer_token_vectors.py
src/python/knnPerfTest.py

* Move all tasks previously in ant to gradle (not yet deleted build.xml so ant is still usable)
* Have a wrapper task which run `python src/python/knnPerfTest.py`, the benefit being it will recompile automatically
* `knnPerfTest.py` will now figure out lucene directory (used for class path when executing java class) using `gradle.properties`, also compilation time is using the same property
* Better integrate higher dimension vectors workflow in gradle, people should be able to only use gradle to finish all set ups
* Upgrade gradle to support java21
* let user able to specify lucene version intend to use, to avoid the situation where multiple version of lucene jar exist in same dir and it will load a random one for use
* Move knn index to a specified dir and ignore it in git

Migrate KnnGraphTester workflow to gradle, plus some misc upgrades and optimize

---

src/python/knnPerfTest.py

I'm not sure why KnnPerfTest ever set `enableMemorySegments`, but I don't see any valid reason to do so. The property selects whether or not to use the "newer" MMapDirectory implementation based on the JDK's `MemorySegment`. This implementation is the default in 9x and is actually the only prod impl in Lucene 10. We should remove the prop that disables it.
Additionally, and since KnnPerfTest runs lucene on the classpath, then  we should enable native access to remove the warning from it's usage (lucene uses native access to call madvise)

Remove unnecessary enableMemorySegments from KnnPerfTest

---

gradle/knn.gradle

This commit fixes the location of the `textDocFileName` (enwiki-20120502-lines-1k-fixed-utf8-with-random-label.txt), file location in knn.gradle. It's in the dataDir not the taskDir - at least for me, no?

fix textDocFileName location in knn.gradle

---

gradle/knn.gradle

This commit improves the error output of the gradle compileKnn task when the external lucene build is not found, rather results in a slue of compile errors.
I find this more useful when I make silly mistakes by not updating `external.lucene.repo`, or forgetting to build lucene itself.

Improve gradle compileKnn task error output when external dir not found

---

tasks/wikimedium.10M.nostopwords.tasks
tasks/wikimedium.1M.nostopwords.tasks

I discovered that we already [have support](https://github.com/mikemccand/luceneutil/blob/bdc762a7225792e457ad0c9e65b194535c910a8b/src/main/perf/SearchTask.java#L248) for numeric range faceting tasks but don't seem to be using them in any of our task files. Let's add a few tasks to the wikimedium* benchmarks?
I'm not sure if there's a better way to do this. It's kind of confusing that this just shows up as "range" in the benchmark task output. It might be nice to make this a little easier to understand?

add a few numeric range faceting tasks to wikimedium*

---

src/python/searchBench.py

This makes competitor and baseline run in alternating order instead of keeping the same order for all iterations. This removes non-trivial bias in tests that run the system at full load. The bias comes from the fact that generating the report after each iteration takes macroscopic time but only utilizes a single CPU cor. This allows the CPU to cool down giving the competitor that runs first an advantage on a fully loaded system because it starts on a cooler CPU. There's also other potential biases like that from page-cache utilization and the like that may or may not advantage the first or second run.
I could clearly reproduce a bias for the competitor before this change, making things run in alterating order removes this effect in my testing.
Also:
Removed the dead `t0` while I was at it …

Fix bias towards competitor in searchBench

---

src/python/benchUtil.py

We shouldn't use the population variance when we're clearly sampling. This massively underestimates the variance in some cases, leading to a number of nightlies showing p-values of 0 in the absence of code changes.
Implemented this by using python statistics, should be ok to rely on python 3.8 at this point right?

Use sample-stddev instead of population-stddev in t-test

---

src/main/perf/TaskParser.java
src/python/nightlyBench.py
tasks/wikinightly.tasks

Today a query like
`CombinedHighMed: his interview +combinedFields=titleTokenized^8.0,body` is parsed as a single `CombinedFieldQuery` query that computes scores by summing up the frequencies and document lengths across 4 terms: `title:his^4`, `title:interview^4`, `body:his`, `body:interview`.
This is not what I would like it to do. Instead, I would like it to compute the score of `his` by summing up frequencies and lengths across the `title^8` and `body` fields, compute the score of `interview` likewise, and finally sum up these two scores via a `BooleanQuery`. Said otherwise both `his` and `interview` are each scored with BM25F, but then their BM25F scores are summed up.

Change the way how combined field queries are parsed.

---

.github/workflows/mark-stale-PRs.yml

We've had the workflow [run](https://github.com/mikemccand/luceneutil/actions/runs/13533496740/job/37820696420) and the logs look correct. We can disable `debug-only` to have it start labeling PRs.

Turn off debug mode for stale PR workflow

---

.github/workflows/python.yml
.gitignore
Makefile
pyproject.toml
requirements.txt

There is a lot of python here! We can't be outdone by any fancy gradle build for the java stuff.
Get the basic project dependencies in requirements files, setup formatting, linting, type-checking.
Run these checks to validate PRs and pushes to main branch.
NOTE: basically all lint checks are disabled. Many files are totally disabled due to serious syntax problems: those are on a bad list and should get addressed first. Then checks can be gradually increased.
NOTE: formatting is currently disabled, I'd recommend to decide when to do it and run 'make reformat', uncomment the check in Makefile, and commit the results. Before doing this, I'd really recommend to fix syntax issues first.

Add a simple python CI

---

pyproject.toml
src/python/searchBench.py

Fix circular import dependency in searchBench.py
The error:
```
python3 src/python/localrun.py -source wikimedium10k
Traceback (most recent call last):
File "util/src/python/localrun.py", line 19, in <module>
import competition
File "util/src/python/competition.py", line 24, in <module>
import searchBench
File "util/src/python/searchBench.py", line 23, in <module>
from competition import JAVA_COMMAND
ImportError: cannot import name 'JAVA_COMMAND' from partially initialized module 'competition' (most likely due to a circular import) (util/src/python/competition.py)
```

Fix searchBench.py circular JAVA_COMMAND import

---

build.gradle
gradle/knn.gradle
src/main/build.gradle

I've noticed that when I follow the README and create a fresh workspace it requires some manual gradle changes before build works and Intellij doesn't complain about wrong package names and missing imports.
Following changes streamline the process:
- `src/main/build.gradle`: current setup adds `perf` and `knn` directories themselvs as source dirs, as a result Intellij complains for classes that use "package perf" that they are not in the right place. With this change, main directory "." is added instead, including its perf and knn subdirectories
- `gradle/knn.gradle`: move `luceneFT` check to `doFirst`, to do it as part of the task execution, not parsing. Otherwise it runs before `gradle.properties` file is created in `localSettings` task
- `build.gradle`: throw exception when …

Fix gradle configs so that gradle build works in a fresh workspace

---

src/main/knn/KnnGraphTester.java

OSQ uses a single bit for each dimension: so its
realEncodingByteSize = 1.0/8.0.

Correct vectors memory usage for OSQ

---

.github/dependabot.yml
pyproject.toml
requirements.txt
src/python/WikipediaExtractor.py
src/python/index_sim.py
src/python/segments_to_html.py

The build is failing because dependencies were changing out underneath us. Pin them, but enable dependabot to run (at most once a week) to send upgrade PRs.

fix build, pin dependencies, enable dependabot

---

gradle/wrapper/gradle-wrapper.properties

Lucene now uses gradle 8.14. Running `./gradlew compileKnn` for benchmarks with latest lucene jar gave the following error:
```bash
BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 68
> Unsupported class file major version 68
```
Upgrading gradle to match Lucene fixes this.

Upgrade gradle version to 8.14

---

src/main/knn/IndexerThread.java

Moving `numDocsIndexed.getAndIncrement()` into synchronized block to fix the inconsistent recall issue mentioned in #385

Fix inconsistent recall when running identical benchmarks

---

src/main/knn/KnnGraphTester.java
src/main/knn/KnnIndexer.java

Solve issue mention in #390 
I made two changes in this pull request:
- Disable compound file  for `TieredMergePolicy` to make sure the segments created by index merges is not in the `.cfs` format. 
- Preload vector files before running queries to index to compute exact NNs 
Before & after results when computing exact NN for 100 queries, 5MM doc embeddings, 4K dimension float32
```
BEFORE
took 9205.919 sec to compute brute-force exact matches
AFTER
took 202.213 sec to compute brute-force exact matches
```

Preload vector files before exact NN computation

---

src/main/knn/KnnGraphTester.java
src/main/perf/SearchPerfTest.java
src/python/initial_setup.py
src/python/knnPerfTest.py

https://github.com/mikemccand/luceneutil/issues/388, https://github.com/mikemccand/luceneutil/issues/332
- Add a new parameter `numSearchThread` for KnnGraphTester that allow to specify the number of threads used when executing Knn query concurrently in multiple segments. 
- Also add two new metrics to the result table: 
- `netCPU`: total CPU summed across all threads when KNN query is executed.
- `avgCpuCount`: average CPU  count being utilized when KNN query is executed 
Example result when executing knnPerfTest with different values of `numSearchThread` (0, 2, 5, 10)
```
recall  latency(ms)  netCPU  avgCpuCount    nDoc  topK  fanout  maxConn  beamWidth  quantized  index(s)  index_docs/s  num_segments  index_size(MB)  vec_disk(MB)  vec_RAM(MB)  indexType
0.934        2.648   2.629 …
```

Enable intra-query concurrency and measure net cpu in knnPerfTest

---

src/main/perf/CreateQueries.java
src/python/benchUtil.py

Since https://github.com/apache/lucene/pull/14873 is introduced, the constructor below will fail because the constructor receives a single int is removed. This PR tries to fix that, and a typo by the way.
https://github.com/mikemccand/luceneutil/blob/522d3c377815686ea8a801d6735f68ae69d637d5/src/main/perf/CreateQueries.java#L68-L70

Fix priority queue constructor issue and a typo `coutnOnlyCount`

---

src/python/notation.py

- Off-heap quantized vector scoring for the Lucene99 vector format (09/16)
- Use new OSQ-based Lucene104 quantized vector format (09/25)

Add some KNN annotations
